### ISSUE TITLE
Clean lại toàn bộ data

### ISSUE THREAD

**Issue by thu4n** [thu4n/trackr-client-app#86]
1 tài khoản cho admin, 2 tài khoản cho delivery man, 3 tài khoản cho customer. Yêu cầu điền đầy đủ thông tin và phải điền đàng hoàng.

**Comment by howtodie123** [comment]
Admin: 21522652@gm.uit.edu.vn  123
Deli: 
21520156@gm.uit.edu.vn  123
21520186@gm.uit.edu.vn  123
Customer
21522446@gm.uit.edu.vn 123
KhongSaoDau@gmail.com 123
proisme123123@gmail.com 123
